default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") { "rgenchev" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "password" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  timeout: 5000

development:
  <<: *default
  database: budgeto_development

test:
  <<: *default
  database: budgeto_test
